include:
  - ../jupyter-common/jupyter-common-compose.yaml
services:
  app:
    container_name: "application-server"
    # Using pre-built image from GAR for fast deployments
    image: "us-central1-docker.pkg.dev/wb-twinkly-turnip-8149/clin-abs-repo/test1:20260203"
    user: "jupyter"
    restart: always
    volumes:
      - .:/workspace:cached
    ports:
      - "8888:8888"
      - "5000:5000"
      - "8000:8000"
    networks:
      - app-network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
networks:
  app-network:
    external: true
